/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelsButtom;

import Model.AlbumToOrder;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author markh
 */
public class OrderContentsButtom extends javax.swing.JPanel {
    
    private AlbumToOrder albumToOrder;

    /**
     * Creates new form orderContentsButtom
     */
    public OrderContentsButtom(AlbumToOrder albumToOrder) {
        this.albumToOrder = albumToOrder;
        initComponents();
        setSize(new Dimension(473, 30));
        jL_Title.setText("Title: "+albumToOrder.getAlbum().getTitle());
        jL_Amount.setText("Amount: "+albumToOrder.getAmount());
        jL_Price.setText("Price: "+ albumToOrder.getPrice());
        jL_type.setText("Type: "+albumToOrder.getAlbum().getPlateType().getType());
        checkStock();
    }
    
    public void checkStock(){
        if (albumToOrder.getAmount() <= albumToOrder.getAlbum().getStock()) {
            jL_Amount.setForeground(Color.green);
        }else{
            jL_Amount.setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Title = new javax.swing.JLabel();
        jL_Amount = new javax.swing.JLabel();
        jL_Price = new javax.swing.JLabel();
        jL_type = new javax.swing.JLabel();

        jL_Title.setText("jLabel1");

        jL_Amount.setText("jLabel1");

        jL_Price.setText("jLabel1");

        jL_type.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_type, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jL_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jL_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jL_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_Amount;
    private javax.swing.JLabel jL_Price;
    private javax.swing.JLabel jL_Title;
    private javax.swing.JLabel jL_type;
    // End of variables declaration//GEN-END:variables
}
